FLASK_APP=app.py 
FLASK_ENV=development
FLASK_DEBUG=1
FLASK_RUN_PORT=8000
FLASK_RUN_HOST="127.0.0.1"
SECRET_KEY="FLASK_MVC"

# Development settings
DOMAIN=example.org
ADMIN_EMAIL=admin@${DOMAIN}
ROOT_URL=${DOMAIN}/app